### ISSUE TITLE
Set VLAN id on dvp to a specific integer

### ISSUE THREAD

**Issue by jonathanmier** [rreubenur/vmware-pyvmomi-examples#15]
Is there a way to set the VLAN id in s portgroup to a specific value instead of a range of values?

**Comment by reubenur-rahman** [comment]
That's easy. Tomorrow I will reply you

**Comment by jonathanmier** [comment]
I figured this out already but I would like to know how to change specs on a DVPortgroup once it is created. Say I want to change the VLAN id to something different.
@rreubenur

**Comment by jonathanmier** [comment]
@rreubenur nvm got it. Thanks.

**Comment by reubenur-rahman** [comment]
dv_pg_spec = vim.dvs.DistributedVirtualPortgroup.ConfigSpec()
dv_pg_spec.defaultPortConfig =
vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy()
-----------------------------------------------------------------------------------------------------------------------------
dv_pg_spec.defaultPortConfig.vlan =
vim.dvs.VmwareDistributedVirtualSwitch.VlanIdSpec()
dv_pg_spec.defaultPortConfig.vlan.vlanId = <vlan_id>
-----------------------------------------------------------------------------------------------------------------------------
dv_pg_spec.defaultPortConfig.vlan =
vim.dvs.VmwareDistributedVirtualSwitch.TrunkVlanSpec()
dv_pg_spec.defaultPortConfig.vlan.vlanId = [vim.NumericRange(start=1,
end=4094)]
-----------------------------------------------------------------------------------------------------------------------------
reconfig_task = pg_obj.ReconfigureDVPortgroup_Task(spec=dv_pg_spec)

task.waitForTask(reconfig_task, si)
