### ISSUE TITLE
Getting a problem adding a virtual nic. 

### ISSUE THREAD

**Issue by jonathanmier** [rreubenur/vmware-pyvmomi-examples#16]
When I use this function 
`def add_virtual_nic(host_network_system, pg_name):` 
from your create_vswitch_and_portgroup.py, I get an error? I created the portgroup and vswitch fine but cant add a vnic. 

Error I get:

vmodl.fault.SecurityError: (vmodl.fault.SecurityError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'vpxapi.fault.NotAuthenticated.summary',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by jonathanmier** [comment]
@rreubenur any clue?

**Comment by reubenur-rahman** [comment]
Not sure but looks like you are messing with the "Management Network" connectivity of the Host which is causing the NotAuthenticated error !

Am I right ? If not then it needs further research ! If yes then try creating a different vSwitch and portgroup and then try to add a vnic there.
Also try the method "AddVirtualNic"
