### ISSUE TITLE
Is there a way to remove a DVPortgorup from DVSwitch?

### ISSUE THREAD

**Issue by jonathanmier** [rreubenur/vmware-pyvmomi-examples#17]
I now you can add a DVPortgroup  to a DVSwitch with CreateDVPortgroup_Task. Is there a way to delete that DVPortgroup?

**Comment by reubenur-rahman** [comment]
Yes directly cal ```Destroy_Task``` on the pg object.

Before doing that verify that the pg is not connected with any VM.
```
vms = pg_obj.summary.vm
if not vms:
    destroy_task = pg_obj.Destroy_Task()
    task.WaitForTask(destroy_task, si)
```

**Comment by jonathanmier** [comment]
Thanks alot
